version: '3.1'

services:
  postgres:
    image: postgres:alpine 
    container_name: dsde
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: eeg
    volumes:
      - ./postgresdata:/var/lib/postgresql/data